name: 'Cloud Integration with S3'
on: [workflow_dispatch]
jobs:
  job1-Configure-AWS-CLI:
    name: 01.Configuring Environment and System
    runs-on: ubuntu-latest
    steps:
      - name: 09.Listing all Recursively
        run: |
          ls /home/runner/work/ -lR
      - name: Configure Environment Variables
        env:
          AWS_ACCESS_KEY_ID:	${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:	${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo ${{ env.AWS_ACCESS_KEY_ID != ''}} ${{ env.AWS_SECRET_ACCESS_KEY != ''}}          
      - name: md5 Function Implementations
        run: |
          result=($(md5sum <(echo env.AWS_SECRET_ACCESS_KEY != '')))
          echo $result
      - name: 09.Listing all Recursively
        run: |
          echo "::set-output name=is_MY_SECRET_set::${{ env.AWS_SECRET_ACCESS_KEY != '' }}"
      - name: 01.Create Folder
        run: |
          mkdir ~/.aws
      - name: 02.Create config file
        run: |
          touch ~/.aws/config
      - name: 03.Update config file
        run: |
          printf '%s\n %s\n %s\n' '[default]' 'region = us-east-1' 'output = table' > ~/.aws/config
      - name: 04.Create credentials file
        run: |
          touch ~/.aws/credentials
      - name: 05.Update credentials file
        run: |
          printf '%s\n %s\n %s\n' '[default]' 'aws_access_key_id = ${{ env.AWS_ACCESS_KEY_ID }}' 'aws_secret_access_key = ${{ env.AWS_SECRET_ACCESS_KEY }}' > ~/.aws/credentials      
      - name: 06.Verify config file 
        run: |
          cat ~/.aws/config
      - name: 07.Verify credentials file 
        run: |
          cat ~/.aws/credentials
      - name: 08.Run AWS S3 LS Command
        run: |
          aws s3 ls
      # - name: Copy Local to S3 using Command
      #   run: |
      #     aws s3 cp ./test.txt s3://bkt28novmujahed/input/local_file.txt  
      